nome = input("Qual é o seu nome? ")
print("Olá, " + nome + "!")
idade = input("Quantos anos você tem? ")
print("Você tem " + idade + " anos.")
print("Bem-vindo ao mundo da programação, " + nome + "!")